<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>FosterExample</AssemblyName>
        <PublishAot>false</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Stageplay.Foster\Stageplay.Foster.csproj" />
    </ItemGroup>

</Project>
