<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>ContentBuilder</AssemblyName>
        <Title>Stageplay MonoGame Content Builder</Title>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>stageplay-monogame-content</ToolCommandName>
        <PackageId>Stageplay.MonoGame.ContentBuilder</PackageId>
        <Description>Content builder tool for Stageplay's MonoGame runtime.</Description>
        <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Stageplay.ContentBuilder\Stageplay.ContentBuilder.csproj" />
        <ProjectReference Include="..\Stageplay.MonoGame\Stageplay.MonoGame.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MonoGame.Framework" Version="$(MonoGameVersion)" />
    </ItemGroup>

</Project>
