namespace Radish.ContentBuilder.AssetProcessors;

/// <summary>
/// The output data from a single <see cref="AssetProcessor.ProcessContentFile"/> invokation.
/// </summary>
/// <param name="GeneratedFiles">A list of files generated by the output of the asset processor.</param>
public record AssetProcessorResult(IReadOnlyList<string> GeneratedFiles);
