<Project Sdk="Microsoft.NET.Sdk">
    
  <PropertyGroup>
    <Description>Stageplay integration for MonoGame.</Description>
    <Title>Stageplay MonoGame Runtime</Title>
    <RootNamespace>Radish.MonoGame</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="$(MonoGameVersion)">
        <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\Stageplay.Runtime\Stageplay.Runtime.csproj" />
  </ItemGroup>

</Project>
