<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>MonoGameExample</AssemblyName>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Stageplay.Extension.Steamworks\Stageplay.Extension.Steamworks.csproj" />
        <ProjectReference Include="..\..\Stageplay.MonoGame\Stageplay.MonoGame.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MonoGame.Framework" Version="$(MonoGameVersion)" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\Stageplay.Extension.Steamworks\Libraries\win64\*.dll">
            <Link>runtimes\win-x64\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\Stageplay.Extension.Steamworks\Libraries\osx\*.dylib">
            <Link>runtimes\osx\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\Stageplay.Extension.Steamworks\Libraries\linux64\*.so">
            <Link>runtimes\linux-x64\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\Stageplay.Extension.Steamworks\Libraries\linuxarm64\*.so">
            <Link>runtimes\linux-arm64\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <None Update="steam_appid.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>