<Project>
    <PropertyGroup>
        <Product>Stageplay</Product>
        <Authors>Audrey Castillo</Authors>
        <Company>Audrey Castillo</Company>
        <Copyright>Copyright (c) 2026 Audrey Castillo</Copyright>
        <RootNamespace>Radish</RootNamespace>
        <PackageProjectUrl>https://github.com/Valax321/Stageplay</PackageProjectUrl>
        <PackageLicenseExpression>Zlib</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Valax321/Stageplay</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        
        <!-- Frankly I don't even know why this is a warning at all -->
        <NoWarn>CA2255</NoWarn>
    </PropertyGroup>
</Project>