<Project>
    <PropertyGroup>
        <Product>Stageplay</Product>
        <Authors>Audrey Castillo</Authors>
        <Company>audrey.zone</Company>
        <Copyright>Copyright (c) 2026 Audrey Castillo.</Copyright>
        <RootNamespace>Radish</RootNamespace>
        <PackageProjectUrl>https://github.com/Valax321/Stageplay</PackageProjectUrl>
        <PackageLicenseExpression>Zlib</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Valax321/Stageplay</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        
        <!-- Frankly I don't even know why this is a warning at all -->
        <NoWarn>CA2255</NoWarn>
    </PropertyGroup>
    
    <PropertyGroup>
        <JetBrainsAnnotationsVersion>2026.2.0</JetBrainsAnnotationsVersion>
        <LuaCSharpVersion>0.5.6</LuaCSharpVersion>
        <MemoryPackVersion>1.21.4</MemoryPackVersion>
        <MSDependencyInjectionVersion>10.0.12</MSDependencyInjectionVersion>
        <MonoGameVersion>3.8.5.1</MonoGameVersion>
        <ZStringVersion>2.6.0</ZStringVersion>
        <FosterFrameworkVersion>0.4.2</FosterFrameworkVersion>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="GitVersion.MsBuild" Version="6.8.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>