<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>disable</Nullable>
        <RootNamespace>Radish.Steamworks</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        
        <PackageId>Stageplay.Steamworks.Win64</PackageId>
        <Title>Stageplay Steamworks Integration (Windows x64)</Title>
        <Description>Steamworks integration package for Stageplay. Built on top of Facepunch.Steamworks. This version must be used on Windows x64 due to struct alignment differences between C compilers. Blame Microsoft.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <!-- Facepunch.Steamworks is missing a bunch of doc comments. Shut em up -->
        <NoWarn>1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <DocumentationFile>bin\$(Configuration)\net10.0\Stageplay.Extension.Steamworks.Win64.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants>$(DefineConstants);PLATFORM_WIN64;PLATFORM_WIN;PLATFORM_64</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Stageplay.Runtime\Stageplay.Runtime.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\thirdparty\Facepunch.Steamworks\Facepunch.Steamworks\**\*.cs">
            <Link>Steamworks\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Libraries\**\*" />
        
        <None Include="Libraries\win64\*.dll">
            <Pack>true</Pack>
            <PackagePath>runtimes/win-x64/native</PackagePath>
        </None>
    </ItemGroup>

</Project>