<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>disable</Nullable>
        <RootNamespace>Radish.Steamworks</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- Note: these only tell you which platform we are BUILDING on, not the runtime target -->
        <RadishIsWindows>$([MSBuild]::IsOSPlatform('Windows'))</RadishIsWindows>
        <RadishIsMac>$([MSBuild]::IsOSPlatform('OSX'))</RadishIsMac>
        <RadishIsLinux>$([MSBuild]::IsOSPlatform('Linux'))</RadishIsLinux>
        <PackageId>Stageplay.Steamworks</PackageId>
        <Title>Stageplay Steamworks Integration</Title>
        <Description>Steamworks integration package for Stageplay. Built on top of Facepunch.Steamworks.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup Condition="$(RadishIsWindows)">
        <DefineConstants>$(DefineConstants);PLATFORM_WIN64;PLATFORM_WIN;PLATFORM_64</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RadishIsMac)' or '$(RadishIsLinux)'">
        <DefineConstants>$(DefineConstants);PLATFORM_POSIX</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Stageplay.Runtime\Stageplay.Runtime.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\thirdparty\Facepunch.Steamworks\Facepunch.Steamworks\**\*.cs">
            <Link>Steamworks\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Libraries\**\*" />
        
        <None Include="Libraries\win64\*.dll">
            <Pack>true</Pack>
            <PackagePath>runtimes/win-x64/native</PackagePath>
        </None>
        <None Include="Libraries\osx\*.dylib">
            <Pack>true</Pack>
            <PackagePath>runtimes/osx/native</PackagePath>
        </None>
        <None Include="Libraries\linux64\*.so">
            <Pack>true</Pack>
            <PackagePath>runtimes/linux-x64/native</PackagePath>
        </None>
        <None Include="Libraries\linuxarm64\*.so">
            <Pack>true</Pack>
            <PackagePath>runtimes/linux-arm64/native</PackagePath>
        </None>
    </ItemGroup>

</Project>